# Generated by Django 4.0.4 on 2022-05-31 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_alter_note_options_alter_note_nt_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='nt_endtime',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 14, 7, 4, 152003), verbose_name='Выполнить к:'),
        ),
    ]
