# Generated by Django 4.0.4 on 2022-06-03 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0003_alter_note_nt_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='nt_endtime',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 13, 28, 55, 174662), verbose_name='Выполнить к:'),
        ),
    ]
